// Ported from dss-validation/src/main/java/eu/europa/esig/dss/validation/reports/AbstractReports.java
// (DSS 6.5.RC1).
//
// Java's AbstractReports declares getXmlSimpleReport() abstract and Print()
// calls it (virtual dispatch onto the concrete Reports/CertificateReports
// subclass). Go has no inheritance, so the shared state and concrete
// methods live on AbstractReportsBase, the subclass-supplied members are
// captured by the AbstractReportsOverrides interface, and each concrete
// wrapper registers itself via InitAbstractReports in its constructor.

package reports

import (
	"github.com/ryftcore/dss-go/dss/detailedreport"
	detailedreportjaxb "github.com/ryftcore/dss-go/dss/detailedreport/jaxb"
	"github.com/ryftcore/dss-go/dss/diagnostic"
	diagnosticjaxb "github.com/ryftcore/dss-go/dss/diagnostic/jaxb"
)

// AbstractReportsOverrides captures the members Java's AbstractReports
// declares abstract (getXmlSimpleReport()) and self-calls from Print().
// Concrete report containers (Reports, CertificateReports) implement it.
type AbstractReportsOverrides interface {
	// GetXmlSimpleReport returns an XML representation of the JAXB
	// SimpleReport. Port of the abstract getXmlSimpleReport().
	GetXmlSimpleReport() (string, error)
}

// AbstractReportsBase is a container for all reports generated by the
// validation process: diagnostic data, detailed report and simple report.
// Port of AbstractReports.
type AbstractReportsBase struct {
	// ValidateXml checks if the XML of reports shall be validated. Port of
	// the protected validateXml field.
	ValidateXml bool

	diagnosticDataWrapper *diagnostic.DiagnosticData
	detailedReportWrapper *detailedreport.DetailedReport

	xmlDiagnosticData string
	xmlDetailedReport string

	// overrides points back at the concrete report container; see
	// InitAbstractReports.
	overrides AbstractReportsOverrides
}

// NewAbstractReportsBase is the default constructor to instantiate the
// shared container state. Port of the protected
// AbstractReports(XmlDiagnosticData, XmlDetailedReport) constructor.
func NewAbstractReportsBase(diagnosticDataJaxb *diagnosticjaxb.XmlDiagnosticData,
	detailedReport *detailedreportjaxb.XmlDetailedReport) AbstractReportsBase {
	return AbstractReportsBase{
		diagnosticDataWrapper: diagnostic.NewDiagnosticData(diagnosticDataJaxb),
		detailedReportWrapper: detailedreport.NewDetailedReport(detailedReport),
	}
}

// InitAbstractReports registers the concrete report container so that base
// methods (Print) can call back into its overridden members. Every
// concrete constructor must call this before use.
func (a *AbstractReportsBase) InitAbstractReports(overrides AbstractReportsOverrides) {
	a.overrides = overrides
}

// reportsOverrides returns the registered overrides, panicking when the
// concrete wrapper failed to call InitAbstractReports.
func (a *AbstractReportsBase) reportsOverrides() AbstractReportsOverrides {
	if a.overrides == nil {
		panic("reports: AbstractReportsBase used without InitAbstractReports")
	}
	return a.overrides
}

// SetValidateXml sets if the XML shall be validated. Port of
// setValidateXml(boolean).
func (a *AbstractReportsBase) SetValidateXml(validateXml bool) {
	a.ValidateXml = validateXml
}

// GetDiagnosticData returns the reference to the diagnostic data object
// generated during the validation process. Port of getDiagnosticData().
func (a *AbstractReportsBase) GetDiagnosticData() *diagnostic.DiagnosticData {
	return a.diagnosticDataWrapper
}

// GetDetailedReport returns the wrapper to manipulate the JAXB
// DetailedReport. Port of getDetailedReport().
func (a *AbstractReportsBase) GetDetailedReport() *detailedreport.DetailedReport {
	return a.detailedReportWrapper
}

// GetDiagnosticDataJaxb returns the JAXB DiagnosticData. Port of
// getDiagnosticDataJaxb().
func (a *AbstractReportsBase) GetDiagnosticDataJaxb() *diagnosticjaxb.XmlDiagnosticData {
	return a.diagnosticDataWrapper.JaxbModel()
}

// GetDetailedReportJaxb returns the JAXB DetailedReport. Port of
// getDetailedReportJaxb().
func (a *AbstractReportsBase) GetDetailedReportJaxb() *detailedreportjaxb.XmlDetailedReport {
	return a.detailedReportWrapper.JAXBModel()
}

// GetXmlDiagnosticData returns the XML representation of the JAXB
// DiagnosticData string. Port of getXmlDiagnosticData().
func (a *AbstractReportsBase) GetXmlDiagnosticData() (string, error) {
	if a.xmlDiagnosticData == "" {
		xml, err := diagnostic.NewDiagnosticDataFacade().Marshal(a.GetDiagnosticDataJaxb())
		if err != nil {
			return "", NewDSSReportExceptionMessageCause("An error occurred during marshalling of JAXB Diagnostic Data", err)
		}
		a.xmlDiagnosticData = xml
	}
	return a.xmlDiagnosticData, nil
}

// GetXmlDetailedReport returns the XML representation of the JAXB
// DetailedReport string. Port of getXmlDetailedReport().
func (a *AbstractReportsBase) GetXmlDetailedReport() (string, error) {
	if a.xmlDetailedReport == "" {
		xml, err := detailedreport.NewDetailedReportFacade().Marshal(a.GetDetailedReportJaxb())
		if err != nil {
			return "", NewDSSReportExceptionMessageCause("An error occurred during marshalling of JAXB Detailed Report", err)
		}
		a.xmlDetailedReport = xml
	}
	return a.xmlDetailedReport, nil
}

// Print writes the reports to stdout, for debug purpose. Port of print(),
// dispatching the abstract getXmlSimpleReport() through the registered
// overrides.
func (a *AbstractReportsBase) Print() {
	println("----------------Diagnostic data-----------------")
	xmlDiagnosticData, err := a.GetXmlDiagnosticData()
	if err != nil {
		xmlDiagnosticData = err.Error()
	}
	println(xmlDiagnosticData)
	println("----------------Validation report---------------")
	xmlDetailedReport, err := a.GetXmlDetailedReport()
	if err != nil {
		xmlDetailedReport = err.Error()
	}
	println(xmlDetailedReport)
	println("----------------Simple report-------------------")
	xmlSimpleReport, err := a.reportsOverrides().GetXmlSimpleReport()
	if err != nil {
		xmlSimpleReport = err.Error()
	}
	println(xmlSimpleReport)
	println("------------------------------------------------")
}
