// Ported from dss-validation/src/main/java/eu/europa/esig/dss/validation/reports/CertificateReports.java
// (DSS 6.5.RC1).

package reports

import (
	detailedreportjaxb "github.com/ryftcore/dss-go/dss/detailedreport/jaxb"
	diagnosticjaxb "github.com/ryftcore/dss-go/dss/diagnostic/jaxb"
	"github.com/ryftcore/dss-go/dss/simplecertificatereport"
	simplecertificatereportjaxb "github.com/ryftcore/dss-go/dss/simplecertificatereport/jaxb"
)

// CertificateReports is a container for all reports generated by the
// certificate validation process: diagnostic data, detailed report and
// simple report. Port of CertificateReports.
type CertificateReports struct {
	AbstractReportsBase

	simpleReportWrapper *simplecertificatereport.SimpleCertificateReport
	xmlSimpleReport     string
}

// NewCertificateReports is the default constructor to instantiate this
// container. Port of CertificateReports(XmlDiagnosticData, XmlDetailedReport,
// XmlSimpleCertificateReport).
func NewCertificateReports(diagnosticDataJaxb *diagnosticjaxb.XmlDiagnosticData,
	detailedReport *detailedreportjaxb.XmlDetailedReport,
	simpleReport *simplecertificatereportjaxb.XmlSimpleCertificateReport) *CertificateReports {
	r := &CertificateReports{
		AbstractReportsBase: NewAbstractReportsBase(diagnosticDataJaxb, detailedReport),
		simpleReportWrapper: simplecertificatereport.NewSimpleCertificateReport(simpleReport),
	}
	r.InitAbstractReports(r)
	return r
}

// GetSimpleReport returns the wrapper to manipulate the JAXB
// SimpleCertificateReport. Port of getSimpleReport().
func (r *CertificateReports) GetSimpleReport() *simplecertificatereport.SimpleCertificateReport {
	return r.simpleReportWrapper
}

// GetSimpleReportJaxb returns the JAXB XmlSimpleCertificateReport. Port of
// getSimpleReportJaxb().
func (r *CertificateReports) GetSimpleReportJaxb() *simplecertificatereportjaxb.XmlSimpleCertificateReport {
	return r.simpleReportWrapper.GetJaxbModel()
}

// GetXmlSimpleReport returns the XML representation of the JAXB
// XmlSimpleCertificateReport string. Port of getXmlSimpleReport().
func (r *CertificateReports) GetXmlSimpleReport() (string, error) {
	if r.xmlSimpleReport == "" {
		xml, err := simplecertificatereport.NewSimpleCertificateReportFacade().Marshal(r.GetSimpleReportJaxb())
		if err != nil {
			return "", NewDSSReportExceptionMessageCause("An error occurred during marshalling of JAXB Simple Report", err)
		}
		r.xmlSimpleReport = xml
	}
	return r.xmlSimpleReport, nil
}
