// Ported from dss-validation/src/main/java/eu/europa/esig/dss/validation/reports/Reports.java
// (DSS 6.5.RC1).
//
// This file depends on the specs-validation-report module's Go port
// (dss/validationreport + dss/validationreport/jaxb, exposing
// ValidationReportFacade and jaxb.ValidationReportType). The import path and
// API shape below mirror ValidationReportFacade.newFacade().marshall(T,
// boolean) as a Marshal(T) (string, error) method, the same shape every
// other report facade in this package uses.

package reports

import (
	detailedreportjaxb "github.com/ryftcore/dss-go/dss/detailedreport/jaxb"
	diagnosticjaxb "github.com/ryftcore/dss-go/dss/diagnostic/jaxb"
	"github.com/ryftcore/dss-go/dss/simplereport"
	simplereportjaxb "github.com/ryftcore/dss-go/dss/simplereport/jaxb"
	"github.com/ryftcore/dss-go/dss/validationreport"
	validationreportjaxb "github.com/ryftcore/dss-go/dss/validationreport/jaxb"
)

// Reports is a container for all reports generated by the signature
// validation process: diagnostic data, detailed report and simple report.
// Port of Reports.
type Reports struct {
	AbstractReportsBase

	simpleReportWrapper *simplereport.SimpleReport
	xmlSimpleReport     string

	etsiValidationReport    *validationreportjaxb.ValidationReportType
	xmlEtsiValidationReport string
}

// NewReports is the default constructor to instantiate this container.
// Port of Reports(XmlDiagnosticData, XmlDetailedReport, XmlSimpleReport,
// ValidationReportType).
func NewReports(diagnosticDataJaxb *diagnosticjaxb.XmlDiagnosticData,
	detailedReport *detailedreportjaxb.XmlDetailedReport,
	simpleReport *simplereportjaxb.XmlSimpleReport,
	validationReport *validationreportjaxb.ValidationReportType) *Reports {
	r := &Reports{
		AbstractReportsBase:  NewAbstractReportsBase(diagnosticDataJaxb, detailedReport),
		simpleReportWrapper:  simplereport.NewSimpleReport(simpleReport),
		etsiValidationReport: validationReport,
	}
	r.InitAbstractReports(r)
	return r
}

// GetSimpleReport returns the wrapper to manipulate the JAXB SimpleReport.
// Port of getSimpleReport().
func (r *Reports) GetSimpleReport() *simplereport.SimpleReport {
	return r.simpleReportWrapper
}

// GetSimpleReportJaxb returns the JAXB SimpleReport. Port of
// getSimpleReportJaxb().
func (r *Reports) GetSimpleReportJaxb() *simplereportjaxb.XmlSimpleReport {
	return r.simpleReportWrapper.GetJaxbModel()
}

// GetEtsiValidationReportJaxb returns the JAXB EtsiValidationReport. Port
// of getEtsiValidationReportJaxb().
func (r *Reports) GetEtsiValidationReportJaxb() *validationreportjaxb.ValidationReportType {
	return r.etsiValidationReport
}

// GetXmlSimpleReport returns the XML representation of the JAXB
// SimpleReport String. Port of getXmlSimpleReport().
func (r *Reports) GetXmlSimpleReport() (string, error) {
	if r.xmlSimpleReport == "" {
		xml, err := simplereport.NewSimpleReportFacade().Marshal(r.GetSimpleReportJaxb())
		if err != nil {
			return "", NewDSSReportExceptionMessageCause("An error occurred during marshalling of JAXB Simple Report", err)
		}
		r.xmlSimpleReport = xml
	}
	return r.xmlSimpleReport, nil
}

// GetXmlValidationReport returns the XML representation of the JAXB ETSI
// Validation Report String. Port of getXmlValidationReport().
func (r *Reports) GetXmlValidationReport() (string, error) {
	if r.xmlEtsiValidationReport == "" {
		xml, err := validationreport.NewValidationReportFacade().Marshal(r.GetEtsiValidationReportJaxb())
		if err != nil {
			return "", NewDSSReportExceptionMessageCause("An error occurred during marshalling of JAXB Etsi Validation Report", err)
		}
		r.xmlEtsiValidationReport = xml
	}
	return r.xmlEtsiValidationReport, nil
}

// Print writes the reports to stdout, for debug purpose. Port of the
// overridden print(), which additionally prints the ETSI validation
// report.
func (r *Reports) Print() {
	println("----------------Diagnostic data-----------------")
	xmlDiagnosticData, err := r.GetXmlDiagnosticData()
	if err != nil {
		xmlDiagnosticData = err.Error()
	}
	println(xmlDiagnosticData)
	println("----------------Validation report---------------")
	xmlDetailedReport, err := r.GetXmlDetailedReport()
	if err != nil {
		xmlDetailedReport = err.Error()
	}
	println(xmlDetailedReport)
	println("----------------Simple report-------------------")
	xmlSimpleReport, err := r.GetXmlSimpleReport()
	if err != nil {
		xmlSimpleReport = err.Error()
	}
	println(xmlSimpleReport)
	println("----------------ETSI validation report-------------------")
	if r.etsiValidationReport != nil {
		xmlValidationReport, err := r.GetXmlValidationReport()
		if err != nil {
			xmlValidationReport = err.Error()
		}
		println(xmlValidationReport)
	} else {
		println("---------- ETSI validation report is disabled -----------")
	}
	println("---------------------------------------------------------")
}
