// Package jaxb is the Go form of the JAXB classes generated by dss-policy-jaxb
// (target/generated-sources/xjc/eu/europa/esig/dss/policy/jaxb, from
// src/main/resources/xsd/policy.xsd) into package eu.europa.esig.dss.policy.jaxb.
//
// Per PORTING.md's generated-JAXB rule, the generated classes are grouped into
// schema-area files rather than kept one-file-per-class; every Java class keeps
// its exact name and field order so that encoding/xml reproduces the JAXB RI's
// element sequence and attribute order byte for byte (see xml.go and
// jaxb_root_test.go's oracle-backed marshal-parity KATs, generated by unmarshalling
// upstream's src/main/resources/policy/*.xml through the real JAXB RI and
// re-marshalling - see /tmp .../scratchpad/oracle/PolicyOracle.java, not carried
// into this repository).
package jaxb
