// Companion tables to the generated model, consumed by jaxbCanonical().
//
// The JAXB RI writes `<X/>` for an element with no children but `<X></X>`
// once characters (even the empty string) have been written. encoding/xml
// always writes `<X></X>`, so the canonicaliser collapses empty element
// pairs to the self-closing form unless the element can carry character
// data. textBearingElements lists the element names bound somewhere in the
// schema to a value whose lexical form may be empty (xs:string,
// xs:base64Binary, xs:list); numeric, boolean, dateTime and enumeration
// bindings are omitted because their lexical form is never empty.
//
// A handful of element names are bound to an emptyable simple type in one
// complex type and to a complex type in another (mostly the EAA claim
// model reusing names such as City or Status). complexInParent resolves
// those by the name of the enclosing element.

package jaxb

var textBearingElements = map[string]bool{
	"AnnotationChange":             true,
	"AuthorizedNamespace":          true,
	"Base64Encoded":                true,
	"Binary":                       true,
	"CanonicalizationMethod":       true,
	"City":                         true,
	"CommonName":                   true,
	"ContactInfo":                  true,
	"ContentHints":                 true,
	"ContentIdentifier":            true,
	"ContentType":                  true,
	"CountryCode":                  true,
	"CountryName":                  true,
	"DAIdentifier":                 true,
	"DataElement":                  true,
	"Description":                  true,
	"DigestValue":                  true,
	"DisclosableClaim":             true,
	"DocumentName":                 true,
	"DocumentType":                 true,
	"Email":                        true,
	"EntityKey":                    true,
	"ErrorMessage":                 true,
	"ExplicitText":                 true,
	"ExtensionChange":              true,
	"Field":                        true,
	"Filename":                     true,
	"Filter":                       true,
	"GivenName":                    true,
	"Id":                           true,
	"Identifier":                   true,
	"Issuer":                       true,
	"IssuerDistinguishedName":      true,
	"IssuerEntityKey":              true,
	"IssuerName":                   true,
	"IssuerSerial":                 true,
	"KID":                          true,
	"KeyLengthUsedToSignThisToken": true,
	"Locality":                     true,
	"Location":                     true,
	"Message":                      true,
	"MimeType":                     true,
	"MimeTypeContent":              true,
	"Name":                         true,
	"NoticeNumbers":                true,
	"Organization":                 true,
	"OrganizationIdentifier":       true,
	"OrganizationName":             true,
	"OrganizationalUnit":           true,
	"PostOfficeBoxNumber":          true,
	"PostalAddress":                true,
	"PostalCode":                   true,
	"ProcessingError":              true,
	"ProfileId":                    true,
	"Pseudonym":                    true,
	"PublicKey":                    true,
	"QcIdentMethod":                true,
	"Reason":                       true,
	"ReferencedName":               true,
	"Role":                         true,
	"SemanticsIdentifier":          true,
	"ServiceType":                  true,
	"SigPolDocLocalURI":            true,
	"SignatureFilename":            true,
	"SignatureOrFormFill":          true,
	"SignatureType":                true,
	"SignatureValue":               true,
	"SignerName":                   true,
	"Ski":                          true,
	"SourceAddress":                true,
	"State":                        true,
	"StateOrProvince":              true,
	"Status":                       true,
	"StreetAddress":                true,
	"SubFilter":                    true,
	"Subject":                      true,
	"SubjectDistinguishedName":     true,
	"SubjectSerialNumber":          true,
	"Surname":                      true,
	"TLSCertificateBindingUrl":     true,
	"TSAGeneralName":               true,
	"Text":                         true,
	"TimestampFilename":            true,
	"Title":                        true,
	"TrustServiceLegalIdentifier":  true,
	"Type":                         true,
	"Undefined":                    true,
	"Uri":                          true,
	"Url":                          true,
	"Version":                      true,
	"X509Url":                      true,
	"ZipComment":                   true,
	"authSourceIdentification":     true,
	"authorityCertIssuerSerial":    true,
	"caIssuersUrl":                 true,
	"countryOfLegislation":         true,
	"crlUrl":                       true,
	"currency":                     true,
	"extendedKeyUsageOid":          true,
	"keyIdentifier":                true,
	"legislationIdentification":    true,
	"name":                         true,
	"ncaId":                        true,
	"ncaName":                      true,
	"ocspUrl":                      true,
	"octets":                       true,
	"oid":                          true,
	"ski":                          true,
	"subjectAlternativeName":       true,
}

var complexInParent = map[string]map[string]bool{
	"Address": {
		"City":            true,
		"CountryName":     true,
		"PostalAddress":   true,
		"PostalCode":      true,
		"StateOrProvince": true,
		"StreetAddress":   true,
	},
	"CredentialSubject": {
		"Email":     true,
		"GivenName": true,
		"Pseudonym": true,
		"Title":     true,
	},
	"EAAPayload": {
		"DocumentType":     true,
		"Email":            true,
		"GivenName":        true,
		"Identifier":       true,
		"Issuer":           true,
		"OrganizationName": true,
		"Pseudonym":        true,
		"Status":           true,
		"Subject":          true,
		"Title":            true,
		"Version":          true,
	},
	"IdentifierList": {
		"Identifier": true,
		"Uri":        true,
	},
	"PlaceOfBirth": {
		"City": true,
	},
	"Status": {
		"Type": true,
		"Uri":  true,
	},
	"StatusList": {
		"Uri": true,
	},
	"SubjectId": {
		"GivenName": true,
	},
}
