package xmldsig_test

import (
	"bufio"
	"bytes"
	"crypto"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"math/big"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"golang.org/x/crypto/cryptobyte"
	cbasn1 "golang.org/x/crypto/cryptobyte/asn1"

	"github.com/utain/esig/dss/enumerations"
	"github.com/utain/esig/dss/internal/xmldom"
	"github.com/utain/esig/dss/internal/xmldsig"
	"github.com/utain/esig/dss/model"
	"github.com/utain/esig/dss/spi"
)

// The known-answer tests: for every ds:Reference of every ds:Signature in the real upstream
// dss-xades fixtures under testdata/corpus, the pre-digest octets, the digest and the
// verification verdict must equal Apache Santuario 3.0.6's, and so must the canonicalized
// ds:SignedInfo and the verdict of checking ds:SignatureValue over it.
//
// testdata/manifest.txt and testdata/golden/* are generated by gen/XmlDsigOracle.java and are
// Java's answers only; see gen/generate.sh. Nothing in this file may be "fixed" by
// regenerating them.
//
// Row kinds, as the oracle writes them:
//
//	signedinfo   golden = the canonicalized ds:SignedInfo octets
//	sigvalue     status = "true" / "false" / "nokey" / "!<JavaException>"
//	refbytes     golden = the transform-pipeline output that gets digested
//	refdigest    status = the hex digest of those octets
//	refverify    status = "true" / "false" / "!<JavaException>"
//	manN.bytes / manN.digest / manN.verify   the same, for the ds:Manifest reference N points at

type katRow struct {
	fixture string
	sig     string
	kind    string
	index   string
	detail  string
	golden  string
	sha256  string
	status  string
}

func loadManifest(t *testing.T) []katRow {
	t.Helper()
	f, err := os.Open(filepath.Join("testdata", "manifest.txt"))
	if err != nil {
		t.Fatalf("open manifest: %v", err)
	}
	defer f.Close()

	var rows []katRow
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 1<<20), 1<<20)
	for sc.Scan() {
		line := sc.Text()
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		p := strings.Split(line, "\t")
		if len(p) != 8 {
			t.Fatalf("malformed manifest line (%d fields): %q", len(p), line)
		}
		rows = append(rows, katRow{p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7]})
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("read manifest: %v", err)
	}
	if len(rows) == 0 {
		t.Fatal("manifest is empty")
	}
	return rows
}

// detachedFor reads gen/cases.txt for the detached documents a fixture must be given.
func detachedFor(t *testing.T) map[string][]string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", "gen", "cases.txt"))
	if err != nil {
		t.Fatalf("open cases: %v", err)
	}
	out := map[string][]string{}
	for _, line := range strings.Split(string(b), "\n") {
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		p := strings.Split(line, "\t")
		if len(p) > 1 && p[1] != "" {
			out[p[0]] = strings.Split(p[1], ",")
		}
	}
	return out
}

// fixtureState is one parsed corpus document with its signatures, built once per fixture.
type fixtureState struct {
	doc        *xmldom.Node
	signatures []*xmldom.Node
	detached   []model.DSSDocument
}

func loadFixture(t *testing.T, name string, detachedNames []string) *fixtureState {
	t.Helper()
	src, err := os.ReadFile(filepath.Join("testdata", "corpus", filepath.FromSlash(name)))
	if err != nil {
		t.Fatalf("read fixture %s: %v", name, err)
	}
	doc, err := xmldom.Parse(src, nil)
	if err != nil {
		t.Fatalf("parse fixture %s: %v", name, err)
	}
	// XAdESSignature.getSantuarioSignature: recursiveIdBrowse before anything else, or no
	// "#id" reference resolves.
	doc.RegisterIDs()

	var sigs []*xmldom.Node
	doc.Walk(func(n *xmldom.Node) bool {
		if n.Kind == xmldom.Element && n.Name.Space == xmldsig.NamespaceDSig && n.Name.Local == "Signature" {
			sigs = append(sigs, n)
		}
		return true
	})

	st := &fixtureState{doc: doc, signatures: sigs}
	for _, dn := range detachedNames {
		b, err := os.ReadFile(filepath.Join("testdata", "corpus", filepath.FromSlash(dn)))
		if err != nil {
			t.Fatalf("read detached %s: %v", dn, err)
		}
		st.detached = append(st.detached, model.NewInMemoryDocumentWithName(b, filepath.Base(dn)))
	}
	return st
}

// newSignature builds the XMLSignature exactly as XAdESSignature does: secure validation off,
// the DSS resolver set, and one detached resolver per distinct reference digest algorithm.
func newSignature(t *testing.T, st *fixtureState, sigEl *xmldom.Node) *xmldsig.XMLSignature {
	t.Helper()
	sig, err := xmldsig.NewXMLSignature(sigEl, &xmldsig.ManifestOptions{})
	if err != nil {
		t.Fatalf("NewXMLSignature: %v", err)
	}
	if len(st.detached) > 0 {
		sig.AddResourceResolver(&xmldsig.DetachedSignatureResolver{
			Documents:       st.detached,
			DigestAlgorithm: enumerations.DigestAlgorithm_SHA256,
		})
	}
	return sig
}

func TestKnownAnswers(t *testing.T) {
	rows := loadManifest(t)
	detached := detachedFor(t)

	// Group rows by fixture so each document is parsed once.
	byFixture := map[string][]katRow{}
	var order []string
	for _, r := range rows {
		if _, seen := byFixture[r.fixture]; !seen {
			order = append(order, r.fixture)
		}
		byFixture[r.fixture] = append(byFixture[r.fixture], r)
	}

	var checked int
	for _, fixture := range order {
		fixture := fixture
		t.Run(fixture, func(t *testing.T) {
			st := loadFixture(t, fixture, detached[fixture])
			for _, row := range byFixture[fixture] {
				checked += runRow(t, st, row)
			}
		})
	}
	if checked == 0 {
		t.Fatal("no known answer was actually checked")
	}
	t.Logf("checked %d known answers over %d fixtures", checked, len(order))
}

func runRow(t *testing.T, st *fixtureState, row katRow) int {
	t.Helper()
	sigIndex, err := strconv.Atoi(row.sig)
	if err != nil || sigIndex >= len(st.signatures) {
		t.Errorf("%s: manifest names signature %q, document has %d", row.kind, row.sig, len(st.signatures))
		return 0
	}
	name := row.kind + "[" + row.index + "]"

	switch {
	// A fixture Santuario could not even open a ds:Signature on: the whole XMLSignature
	// constructor threw, so there is nothing further to compare and the only thing this
	// port owes is the same refusal. validation/xades-unsupported-signature-algorithm.xml
	// is the corpus's one instance.
	case row.kind == "signature":
		t.Run("signature", func(t *testing.T) {
			if _, err := xmldsig.NewXMLSignature(st.signatures[sigIndex], &xmldsig.ManifestOptions{}); err != nil {
				return
			}
			// Santuario rejects it inside the constructor; this port defers the
			// ds:SignatureMethod check to verification time, so the refusal must show
			// up there instead. Anything that gets a verdict out of it is a divergence.
			sig, _ := xmldsig.NewXMLSignature(st.signatures[sigIndex], &xmldsig.ManifestOptions{})
			pub := keyInfoPublicKey(sig)
			if pub == nil {
				t.Skipf("Java failed with %s; no key here to reach the same refusal with", row.status)
			}
			if ok, err := sig.CheckSignatureValueOnly(pub); err == nil {
				t.Fatalf("Java failed with %s, Go answered %t", row.status, ok)
			}
		})
	case row.kind == "signedinfo":
		t.Run(name, func(t *testing.T) {
			sig := newSignature(t, st, st.signatures[sigIndex])
			got, err := sig.SignedInfo().CanonicalizedOctets()
			checkBytes(t, row, got, err)
		})
	case row.kind == "sigvalue":
		t.Run(name, func(t *testing.T) {
			sig := newSignature(t, st, st.signatures[sigIndex])
			checkSignatureValue(t, st, sig, row)
		})
	case strings.HasSuffix(row.kind, "bytes"):
		t.Run(name, func(t *testing.T) {
			ref := reference(t, st, sigIndex, row)
			if ref == nil {
				checkBytes(t, row, nil, errors.New("reference not reachable"))
				return
			}
			got, err := ref.ReferencedBytes()
			checkBytes(t, row, got, err)
		})
	case strings.HasSuffix(row.kind, "digest"):
		t.Run(name, func(t *testing.T) {
			ref := reference(t, st, sigIndex, row)
			if ref == nil {
				checkLiteral(t, row, "-")
				return
			}
			got, err := ref.ReferencedBytes()
			if err != nil {
				checkLiteral(t, row, "-")
				return
			}
			alg, err := ref.DigestAlgorithm()
			if err != nil {
				checkLiteral(t, row, "!"+err.Error())
				return
			}
			d, err := spi.DSSUtilsDigest(alg, got)
			if err != nil {
				checkLiteral(t, row, "!"+err.Error())
				return
			}
			checkLiteral(t, row, hex.EncodeToString(d))
		})
	case strings.HasSuffix(row.kind, "verify"):
		t.Run(name, func(t *testing.T) {
			ref := reference(t, st, sigIndex, row)
			if ref == nil {
				checkVerdict(t, row, false, errors.New("reference not reachable"))
				return
			}
			ok, err := ref.Verify()
			checkVerdict(t, row, ok, err)
		})
	default:
		t.Errorf("unknown manifest row kind %q", row.kind)
		return 0
	}
	return 1
}

// reference resolves a manifest row's kind+index to a *xmldsig.Reference: "ref*" rows address
// the signature's own ds:SignedInfo, "manN.*" rows the ds:Manifest that reference N points at.
func reference(t *testing.T, st *fixtureState, sigIndex int, row katRow) *xmldsig.Reference {
	t.Helper()
	sig := newSignature(t, st, st.signatures[sigIndex])
	idx, err := strconv.Atoi(row.index)
	if err != nil {
		t.Fatalf("bad index %q", row.index)
	}

	if strings.HasPrefix(row.kind, "ref") {
		ref, err := sig.SignedInfo().Item(idx)
		if err != nil {
			t.Fatalf("SignedInfo.Item(%d): %v", idx, err)
		}
		return ref
	}

	// manN.<kind>
	outer, err := strconv.Atoi(strings.TrimPrefix(strings.Split(row.kind, ".")[0], "man"))
	if err != nil {
		t.Fatalf("bad manifest row kind %q", row.kind)
	}
	outerRef, err := sig.SignedInfo().Item(outer)
	if err != nil {
		t.Fatalf("SignedInfo.Item(%d): %v", outer, err)
	}
	manEl := manifestByID(st.doc, outerRef.URI())
	if manEl == nil {
		return nil
	}
	man, err := xmldsig.NewManifest(manEl, &xmldsig.ManifestOptions{})
	if err != nil {
		t.Fatalf("NewManifest: %v", err)
	}
	if len(st.detached) > 0 {
		man.AddResourceResolver(&xmldsig.DetachedSignatureResolver{
			Documents:       st.detached,
			DigestAlgorithm: enumerations.DigestAlgorithm_SHA256,
		})
	}
	ref, err := man.Item(idx)
	if err != nil {
		t.Fatalf("Manifest.Item(%d): %v", idx, err)
	}
	return ref
}

// manifestByID mirrors the oracle's lookup: the ds:Manifest whose Id attribute matches the
// "#id" the outer reference names.
func manifestByID(doc *xmldom.Node, uri string) *xmldom.Node {
	if !strings.HasPrefix(uri, "#") {
		return nil
	}
	id := uri[1:]
	var found *xmldom.Node
	doc.Walk(func(n *xmldom.Node) bool {
		if found != nil {
			return false
		}
		if n.Kind == xmldom.Element && n.Name.Space == xmldsig.NamespaceDSig &&
			n.Name.Local == "Manifest" && n.AttrValue("", "Id") == id {
			found = n
		}
		return true
	})
	return found
}

// checkBytes compares a byte golden. An "!ERROR X" status means Java failed, and so must Go -
// the Java exception class is NOT compared, because it names a JCE provider's opinion (the
// brainpool curve, the RSASSA-PSS key size) rather than anything this port decides.
func checkBytes(t *testing.T, row katRow, got []byte, err error) {
	t.Helper()
	if strings.HasPrefix(row.status, "!ERROR") {
		if err == nil {
			t.Fatalf("Java failed with %s, Go produced %d bytes", row.status, len(got))
		}
		return
	}
	if err != nil {
		t.Fatalf("Java produced %s bytes, Go failed: %v", row.sha256[:12], err)
	}
	want, rerr := os.ReadFile(filepath.Join("testdata", "golden", row.golden))
	if rerr != nil {
		t.Fatalf("read golden %s: %v", row.golden, rerr)
	}
	if sum := fmt.Sprintf("%x", sha256.Sum256(want)); sum != row.sha256 {
		t.Fatalf("golden %s is corrupt: manifest says %s, file hashes to %s", row.golden, row.sha256, sum)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("bytes differ from Santuario's\n%s", firstDifference(want, got))
	}
}

func checkLiteral(t *testing.T, row katRow, got string) {
	t.Helper()
	if strings.HasPrefix(row.status, "!") {
		if !strings.HasPrefix(got, "!") && got != "-" {
			t.Fatalf("Java failed with %s, Go answered %s", row.status, got)
		}
		return
	}
	if got != row.status {
		t.Fatalf("Santuario says %s, Go says %s", row.status, got)
	}
}

func checkVerdict(t *testing.T, row katRow, ok bool, err error) {
	t.Helper()
	if strings.HasPrefix(row.status, "!") {
		if err == nil {
			t.Fatalf("Java failed with %s, Go answered %t", row.status, ok)
		}
		return
	}
	if err != nil {
		t.Fatalf("Santuario says %s, Go failed: %v", row.status, err)
	}
	if got := strconv.FormatBool(ok); got != row.status {
		t.Fatalf("Santuario says %s, Go says %s", row.status, got)
	}
}

// checkSignatureValue reproduces the oracle's sigvalue row: verify ds:SignatureValue over the
// canonicalized ds:SignedInfo with the ds:KeyInfo public key, and nothing else.
func checkSignatureValue(t *testing.T, st *fixtureState, sig *xmldsig.XMLSignature, row katRow) {
	t.Helper()
	pub := keyInfoPublicKey(sig)
	switch {
	case row.status == "nokey":
		if pub != nil {
			t.Fatalf("Java found no usable ds:KeyInfo key, Go found a %T", pub)
		}
		return
	case pub == nil && strings.HasPrefix(row.status, "!"):
		// Java could not verify either - the corpus has one RSASSA-PSS key and one brainpool
		// key that neither JCE provider nor crypto/x509 will hand back. Both fail; agreed.
		return
	case pub == nil:
		t.Fatalf("Java answered %s, Go found no ds:KeyInfo public key", row.status)
	}
	ok, err := sig.CheckSignatureValueOnly(pub)
	checkVerdict(t, row, ok, err)
}

// keyInfoPublicKey extracts the signing certificate's public key from ds:KeyInfo. It is the
// port of DSSXMLUtils#getKeyInfoSigningCertificatePublicKey reduced to the one shape the
// corpus uses, ds:X509Data/ds:X509Certificate; building the full org.apache.xml.security.keys
// KeyInfo resolver chain is XAdES-layer work and is not what these known answers pin.
//
// It reads the SubjectPublicKeyInfo out of the DER by hand rather than through
// x509.ParseCertificate, because Go's certificate parser rejects certificates the JDK accepts -
// one fixture carries a critical authorityKeyIdentifier - and this test is about verifying
// signatures, not about certificate hygiene. Where BOTH parsers can produce a key the answers
// must still match Santuario's.
func keyInfoPublicKey(sig *xmldsig.XMLSignature) crypto.PublicKey {
	ki := sig.KeyInfoElement()
	if ki == nil {
		return nil
	}
	var cert *xmldom.Node
	ki.Walk(func(n *xmldom.Node) bool {
		if cert != nil {
			return false
		}
		if n.Kind == xmldom.Element && n.Name.Space == xmldsig.NamespaceDSig &&
			n.Name.Local == "X509Certificate" {
			cert = n
		}
		return true
	})
	if cert == nil {
		return rsaKeyValue(ki)
	}
	der, err := base64.StdEncoding.DecodeString(strings.Join(strings.Fields(cert.TextContent()), ""))
	if err != nil {
		return nil
	}
	if c, err := x509.ParseCertificate(der); err == nil && c.PublicKey != nil {
		return c.PublicKey
	}
	spki, ok := subjectPublicKeyInfo(der)
	if !ok {
		return nil
	}
	pub, err := x509.ParsePKIXPublicKey(spki)
	if err != nil {
		return nil
	}
	return pub
}

// rsaKeyValue reads ds:KeyInfo/ds:KeyValue/ds:RSAKeyValue, the other shape the corpus uses
// (four fixtures carry the bare public key instead of a certificate:
// dss1788/XAdESPublicKeyInKeyInfo.xml, dss1788/dss1788-noCertProvided.xml,
// dss1788/dss1920-cert-in-certValues.xml, xmldsig-only.xml). Santuario reaches it through
// its full KeyInfo resolver chain, which is dss-xades-layer work; here the two elements are
// read directly, since ds:Modulus and ds:Exponent are just base64 big-endian integers.
//
// ds:DSAKeyValue and ds:ECKeyValue are deliberately absent: no corpus fixture uses either,
// and a decoder no known answer exercises is a decoder that cannot be trusted.
func rsaKeyValue(ki *xmldom.Node) crypto.PublicKey {
	var kv *xmldom.Node
	ki.Walk(func(n *xmldom.Node) bool {
		if kv != nil {
			return false
		}
		if n.Kind == xmldom.Element && n.Name.Space == xmldsig.NamespaceDSig && n.Name.Local == "RSAKeyValue" {
			kv = n
		}
		return true
	})
	if kv == nil {
		return nil
	}
	field := func(local string) []byte {
		for _, e := range kv.Elements() {
			if e.Name.Space == xmldsig.NamespaceDSig && e.Name.Local == local {
				b, err := base64.StdEncoding.DecodeString(strings.Join(strings.Fields(e.TextContent()), ""))
				if err != nil {
					return nil
				}
				return b
			}
		}
		return nil
	}
	mod, exp := field("Modulus"), field("Exponent")
	if len(mod) == 0 || len(exp) == 0 {
		return nil
	}
	e := new(big.Int).SetBytes(exp)
	if !e.IsInt64() || e.Int64() <= 0 || e.Int64() > 1<<31-1 {
		return nil
	}
	return &rsa.PublicKey{N: new(big.Int).SetBytes(mod), E: int(e.Int64())}
}

// subjectPublicKeyInfo returns the raw DER of a certificate's SubjectPublicKeyInfo:
// Certificate ::= SEQUENCE { tbsCertificate SEQUENCE { [0] version, serialNumber, signature,
// issuer, validity, subject, subjectPublicKeyInfo, ... }, ... }.
func subjectPublicKeyInfo(der []byte) ([]byte, bool) {
	input := cryptobyte.String(der)
	var certificate, tbs cryptobyte.String
	if !input.ReadASN1(&certificate, cbasn1.SEQUENCE) || !certificate.ReadASN1(&tbs, cbasn1.SEQUENCE) {
		return nil, false
	}
	// The optional explicit [0] version tag.
	tbs.SkipOptionalASN1(cbasn1.Tag(0).Constructed().ContextSpecific())
	for _, tag := range []cbasn1.Tag{
		cbasn1.INTEGER,  // serialNumber
		cbasn1.SEQUENCE, // signature
		cbasn1.SEQUENCE, // issuer
		cbasn1.SEQUENCE, // validity
		cbasn1.SEQUENCE, // subject
	} {
		var field cryptobyte.String
		if !tbs.ReadASN1(&field, tag) {
			return nil, false
		}
	}
	var spki cryptobyte.String
	if !tbs.ReadASN1Element(&spki, cbasn1.SEQUENCE) {
		return nil, false
	}
	return spki, true
}

// firstDifference renders the first differing offset with a little context, which is what one
// actually needs when a canonicalization goes wrong.
func firstDifference(want, got []byte) string {
	n := len(want)
	if len(got) < n {
		n = len(got)
	}
	i := 0
	for i < n && want[i] == got[i] {
		i++
	}
	lo := i - 60
	if lo < 0 {
		lo = 0
	}
	hiWant, hiGot := i+60, i+60
	if hiWant > len(want) {
		hiWant = len(want)
	}
	if hiGot > len(got) {
		hiGot = len(got)
	}
	return fmt.Sprintf("first difference at offset %d (want %d bytes, got %d)\nwant: %q\ngot:  %q",
		i, len(want), len(got), want[lo:hiWant], got[lo:hiGot])
}

// TestCheckSignatureValueEndToEnd exercises the whole of XMLSignature#checkSignatureValue -
// canonicalize ds:SignedInfo, verify ds:SignatureValue over it, then re-digest every
// ds:Reference - which the row-by-row known answers only reach in halves.
//
// The expectations are derived from the oracle's own answers: a signature whose sigvalue row
// says true and whose every refverify row says true must come out true; one whose sigvalue is
// true but which has a false refverify must come out false, because checkSignatureValue is the
// conjunction of the two.
func TestCheckSignatureValueEndToEnd(t *testing.T) {
	for _, tc := range []struct {
		fixture string
		sig     int
		want    bool
	}{
		{"validation/dss-signed.xml", 0, true},
		{"validation/doubleSignedTest.xml", 0, true},
		{"validation/doubleSignedTest.xml", 1, true},
		{"validation/dss1135/factura_ejemplo2_32v1.xml", 0, true},
		// A wrapping attack: the ds:SignatureValue still verifies over ds:SignedInfo, and the
		// references still resolve, because the attacker kept the signed copy intact - but
		// XSW-enveloped-fake-content is the fixture where DSS's own duplicate-Id detection is
		// what catches it, not the cryptography, so this one is still true here.
		{"validation/xsw/XSW-enveloped-fake-content.xml", 0, true},
		// Signature 1 references the outer ds:SignatureValue and its digest no longer matches.
		{"validation/TEST_S1a_C1a_InTL_VALID.xml", 1, false},
		{"validation/Signature-X-RO_TRA-4.xml", 0, false},
	} {
		tc := tc
		t.Run(tc.fixture+"/"+strconv.Itoa(tc.sig), func(t *testing.T) {
			st := loadFixture(t, tc.fixture, nil)
			sig := newSignature(t, st, st.signatures[tc.sig])
			pub := keyInfoPublicKey(sig)
			if pub == nil {
				t.Fatal("no ds:KeyInfo public key")
			}
			got, err := sig.CheckSignatureValue(pub)
			if err != nil {
				t.Fatalf("CheckSignatureValue: %v", err)
			}
			if got != tc.want {
				t.Fatalf("CheckSignatureValue = %t, want %t", got, tc.want)
			}
		})
	}
}
