// Known-answer tests against the Apache Santuario goldens in testdata/.
//
// The goldens are Java's answers, generated by testdata/gen/C14nOracle.java through the DSS
// call path and checked in; nothing here ever writes one. A golden that changes in a pull
// request is a red flag.
package xmlc14n

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/utain/esig/dss/internal/corpustest"
	"github.com/utain/esig/dss/internal/xmldom"
)

// implemented maps every algorithm slug the oracle emits to its URI. All seven registered
// algorithms canonicalize, so every manifest line is a live known-answer test; a slug missing
// from this map is a manifest the code does not cover and fails the run.
var implemented = map[string]Algorithm{
	"c14n10":   C14N10,
	"c14n10wc": C14N10WithComments,
	"c14n11":   C14N11,
	"c14n11wc": C14N11WithComments,
	"excl":     C14NExclusive,
	"exclwc":   C14NExclusiveWithComments,
	"phys":     C14NPhysical,
}

type kat struct {
	doc        string
	algSlug    string
	scope      string
	apex       string
	prefixList string
	golden     string
	sha256     string
	status     string
}

func loadManifest(t *testing.T) []kat {
	t.Helper()
	raw, err := os.ReadFile(corpustest.Path(t, "manifest.txt"))
	if err != nil {
		t.Fatalf("read manifest: %v", err)
	}
	var out []kat
	for _, line := range strings.Split(string(raw), "\n") {
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		f := strings.Split(line, "\t")
		if strings.HasPrefix(f[0], "negative/") {
			continue // handled by TestParseRejectsNegativeCorpus
		}
		if len(f) < 8 {
			t.Fatalf("malformed manifest line: %q", line)
		}
		out = append(out, kat{
			doc: f[0], algSlug: f[1], scope: f[2], apex: f[3],
			prefixList: f[4], golden: f[5], sha256: f[6], status: f[7],
		})
	}
	if len(out) == 0 {
		t.Fatal("manifest holds no known-answer tests")
	}
	return out
}

// findApex is the apex selection rule the oracle uses (C14nOracle.findApex): the first element
// in document order carrying an attribute whose local name equals "id" case-insensitively -
// Id, ID, id, xml:id, prefixed or not - with the wanted value. Deliberately not ElementByID,
// which would pin xmldom's ID registration rather than the canonicalizer.
func findApex(n *xmldom.Node, id string) *xmldom.Node {
	if n.Kind == xmldom.Element {
		for _, attr := range n.Attrs {
			if strings.EqualFold(attr.Name.Local, "id") && attr.Value == id {
				return n
			}
		}
	}
	for c := n.FirstChild; c != nil; c = c.NextSibling {
		if found := findApex(c, id); found != nil {
			return found
		}
	}
	return nil
}

func TestC14nGolden(t *testing.T) {
	sources := map[string][]byte{}
	for _, k := range loadManifest(t) {
		alg, ok := implemented[k.algSlug]
		if !ok {
			t.Errorf("manifest names an unknown algorithm slug %q", k.algSlug)
			continue
		}
		t.Run(k.golden, func(t *testing.T) {
			src, ok := sources[k.doc]
			if !ok {
				var err error
				src, err = os.ReadFile(corpustest.Path(t, filepath.Join("corpus", k.doc)))
				if err != nil {
					t.Fatalf("read corpus: %v", err)
				}
				sources[k.doc] = src
			}
			want, err := os.ReadFile(corpustest.Path(t, filepath.Join("golden", k.golden)))
			if err != nil {
				t.Fatalf("read golden: %v", err)
			}
			// A corrupted regeneration must not be able to hide behind a matching Go bug.
			if sum := hex.EncodeToString(sha256Sum(want)); sum != k.sha256 {
				t.Fatalf("golden %s has sha256 %s, manifest says %s", k.golden, sum, k.sha256)
			}

			doc, err := xmldom.Parse(src, nil)
			if err != nil {
				t.Fatalf("parse %s: %v", k.doc, err)
			}
			in := Input{Node: doc}
			if k.apex != "" {
				apex := findApex(doc, k.apex)
				if apex == nil {
					t.Fatalf("no element with an Id/ID/xml:id attribute equal to %q", k.apex)
				}
				in.Node = apex
			}
			if k.prefixList != "" {
				in.InclusivePrefixes = ParsePrefixList(k.prefixList)
			}

			got, err := CanonicalizeToBytes(alg, in)
			if k.status == "ERROR" {
				assertJavaError(t, string(want), err)
				return
			}
			if err != nil {
				t.Fatalf("Canonicalize: %v", err)
			}
			if !bytes.Equal(got, want) {
				t.Errorf("canonical form differs\n got: %q\nwant: %q", got, want)
			}
		})
	}
}

// assertJavaError checks that Go fails where Java failed, and for the same reason. A Go
// success on a Java failure is the interesting direction and must never pass.
func assertJavaError(t *testing.T, golden string, err error) {
	t.Helper()
	javaClass := strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(golden), "!ERROR "))
	if err == nil {
		t.Fatalf("Canonicalize succeeded where Java raised %s", javaClass)
	}
	switch javaClass {
	case "CanonicalizationException":
		var rel *RelativeNamespaceError
		if !errors.As(err, &rel) {
			t.Errorf("error is %v (%T), want *RelativeNamespaceError", err, err)
		}
	case "NullPointerException", "StringIndexOutOfBoundsException":
		// The two unchecked exceptions Santuario's C14N 1.1 xml:base join can raise: an
		// opaque base whose java.net.URI path is null, and an authority-only reference whose
		// empty path removeDotSegments indexes at 0. Neither is caught by XmlAttrStack's
		// catch of URISyntaxException, so the canonicalization fails outright and Go must
		// fail the same way rather than inventing a joined URI.
		if !errors.Is(err, ErrXMLBaseUnjoinable) {
			t.Errorf("error is %v (%T), want ErrXMLBaseUnjoinable", err, err)
		}
	default:
		var syntax *xmldom.SyntaxError
		if !errors.As(err, &syntax) {
			t.Logf("Java raised %s, Go returned %v", javaClass, err)
		}
	}
}

// TestC14nAgainstXMLCanonicalizerCallPath drives the document-scope KATs through
// CanonicalizeBytes, i.e. exactly what XMLCanonicalizer.canonicalize(byte[]) does, so the
// parse-then-canonicalize seam is covered end to end and not only the Node entry point.
func TestC14nAgainstXMLCanonicalizerCallPath(t *testing.T) {
	for _, k := range loadManifest(t) {
		alg, ok := implemented[k.algSlug]
		if !ok || k.scope != "doc" || k.status == "ERROR" {
			continue
		}
		t.Run(k.golden, func(t *testing.T) {
			src, err := os.ReadFile(corpustest.Path(t, filepath.Join("corpus", k.doc)))
			if err != nil {
				t.Fatalf("read corpus: %v", err)
			}
			want, err := os.ReadFile(corpustest.Path(t, filepath.Join("golden", k.golden)))
			if err != nil {
				t.Fatalf("read golden: %v", err)
			}
			got, err := CanonicalizeBytes(alg, src)
			if err != nil {
				t.Fatalf("CanonicalizeBytes: %v", err)
			}
			if !bytes.Equal(got, want) {
				t.Errorf("canonical form differs\n got: %q\nwant: %q", got, want)
			}
		})
	}
}

// TestDOMRoundTrip catches serializer bugs without demanding byte-parity with Java's
// Transformer: whatever Serialize writes must canonicalize to what the original does.
func TestDOMRoundTrip(t *testing.T) {
	entries, err := os.ReadDir(corpustest.Path(t, "corpus"))
	if err != nil {
		t.Fatalf("read corpus dir: %v", err)
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".xml") {
			continue
		}
		t.Run(entry.Name(), func(t *testing.T) {
			src, err := os.ReadFile(filepath.Join(corpustest.Path(t, "corpus"), entry.Name()))
			if err != nil {
				t.Fatalf("read: %v", err)
			}
			doc, err := xmldom.Parse(src, nil)
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			first, err := CanonicalizeNode(C14N10WithComments, doc)
			if err != nil {
				// ns-relative.xml is canonicalization-rejected by design; TestC14nGolden
				// covers that, and there is nothing to round trip.
				t.Skipf("not canonicalizable under C14N 1.0: %v", err)
			}
			serialized, err := doc.Bytes(nil)
			if err != nil {
				t.Fatalf("serialize: %v", err)
			}
			reparsed, err := xmldom.Parse(serialized, nil)
			if err != nil {
				t.Fatalf("reparse %q: %v", serialized, err)
			}
			second, err := CanonicalizeNode(C14N10WithComments, reparsed)
			if err != nil {
				t.Fatalf("canonicalize reparsed: %v", err)
			}
			if !bytes.Equal(first, second) {
				t.Errorf("round trip changed the canonical form\n before: %q\n  after: %q", first, second)
			}
		})
	}
}

// TestParseRejectsNegativeCorpus asserts that every document Java's parsers refuse is refused
// here too. manifest.txt records what Java made of each, including the one deliberate
// divergence: Xerces accepts <?xml version="1.1"?> and applies XML 1.1 line-ending
// normalization, which would silently change canonical bytes, so xmldom rejects it (design
// decision D4, recorded as an accepted gap in PORTING_PLAN.md).
func TestParseRejectsNegativeCorpus(t *testing.T) {
	dir := corpustest.Path(t, filepath.Join("corpus", "negative"))
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read negative dir: %v", err)
	}
	if len(entries) == 0 {
		t.Fatal("negative corpus is empty")
	}
	for _, entry := range entries {
		t.Run(entry.Name(), func(t *testing.T) {
			src, err := os.ReadFile(filepath.Join(dir, entry.Name()))
			if err != nil {
				t.Fatalf("read: %v", err)
			}
			if _, err := xmldom.Parse(src, nil); err == nil {
				t.Errorf("parsed %q, want a SyntaxError", src)
			}
		})
	}
}

func sha256Sum(b []byte) []byte {
	sum := sha256.Sum256(b)
	return sum[:]
}

func FuzzCanonicalize(f *testing.F) {
	entries, err := os.ReadDir(corpustest.Path(f, "corpus"))
	if err != nil {
		f.Fatalf("read corpus dir: %v", err)
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".xml") {
			continue
		}
		src, err := os.ReadFile(filepath.Join(corpustest.Path(f, "corpus"), entry.Name()))
		if err != nil {
			f.Fatalf("read: %v", err)
		}
		f.Add(src)
	}
	f.Fuzz(func(t *testing.T, src []byte) {
		doc, err := xmldom.Parse(src, nil)
		if err != nil {
			return
		}
		for _, alg := range implemented {
			// The physical method is excluded, and not because of a bug here.
			// xmldom.Serialize reproduces OpenJDK's identity Transformer byte for byte,
			// and that serializer drops a namespace declaration that rebinds a prefix to
			// the URI it already has, along with any declaration of the "xml" prefix.
			// Every other algorithm ignores those declarations anyway; physical
			// canonicalization is defined to reproduce them, so a serialize/parse round
			// trip legitimately changes its output - in Java exactly as here. DSS itself
			// makes that round trip in DomUtils.excludeComments.
			if alg == C14NPhysical {
				continue
			}
			first, err := CanonicalizeNode(alg, doc)
			if err != nil {
				continue
			}
			serialized, err := doc.Bytes(nil)
			if err != nil {
				t.Fatalf("serialize: %v", err)
			}
			reparsed, err := xmldom.Parse(serialized, nil)
			if err != nil {
				t.Fatalf("reparse of own output failed: %v", err)
			}
			second, err := CanonicalizeNode(alg, reparsed)
			if err != nil {
				t.Fatalf("canonicalize of round trip failed: %v", err)
			}
			if !bytes.Equal(first, second) {
				t.Fatalf("round trip changed the canonical form under %s", alg)
			}
		}
	})
}
