package xmlc14n

import (
	"errors"
	"strings"
	"testing"

	"github.com/utain/esig/dss/internal/xmldom"
)

// The known-answer tests in testdata/ are the authority on what joinURI must produce: every
// expected value there is Santuario's, generated by gen/C14nOracle.java. The tests in this
// file cover only the defensive paths a corpus document cannot reach - malformed UTF-8, ISO
// control characters, and the physical method's node-set backstop - and they assert
// behaviour (no panic, right error, documented contract), never a byte string that this
// implementation itself produced.

func TestCheckURICharsRejectsControlAndMalformedInput(t *testing.T) {
	bad := []struct {
		name string
		in   string
	}{
		{"malformed utf-8", "http://x/\xff\xfe/"},
		{"lone continuation byte", "a\x80b"},
		{"ISO control above 127", "ab"},
		{"C0 control", "a\x01b"},
		{"truncated escape", "a%4"},
		{"non-hex escape", "a%zz"},
		{"space", "a b"},
		{"double quote", `a"b`},
		{"angle bracket", "a<b"},
		{"backslash", `a\b`},
	}
	for _, tc := range bad {
		t.Run(tc.name, func(t *testing.T) {
			if err := checkURIChars(tc.in); !errors.Is(err, errURISyntax) {
				t.Errorf("checkURIChars(%q) = %v, want errURISyntax", tc.in, err)
			}
		})
	}

	good := []string{
		"", "http://x/a/", "a/b", "%20", "%2F", "café", "中文",
		"a?q=1&r=2", "//host/p", "[::1]", "a;b,c=d+e$f", "-_.!~*'()",
	}
	for _, in := range good {
		if err := checkURIChars(in); err != nil {
			t.Errorf("checkURIChars(%q) = %v, want nil", in, err)
		}
	}
}

// quoteURI's non-ASCII branch is only reachable with a space or control character that
// survived the input scan, which a parsed xml:base cannot carry - checkURIChars rejects those
// on the way in. It stays covered here so that a future caller feeding an unscanned string
// still gets UTF-8 percent-encoding rather than raw bytes.
func TestQuoteURIEncodesNonASCIISpacesAndControls(t *testing.T) {
	cases := []struct{ in, want string }{
		{"a b", "a%C2%A0b"},    // no-break space: isSpaceChar
		{"a b", "a%E2%80%A8b"}, // line separator: isSpaceChar
		{"ab", "a%C2%85b"},    // NEL: isISOControl
		{"café", "café"},       // ordinary non-ASCII passes through
		{"中文", "中文"},
		{"a b", "a%20b"},     // ASCII space is outside L_PATH
		{"a%20b", "a%2520b"}, // '%' is outside L_PATH too, so a raw escape is re-escaped
		{"a/b", "a/b"},
		{"a?b", "a%3Fb"}, // '?' is not in L_PATH
	}
	for _, tc := range cases {
		if got := quoteURI(tc.in, uriAllowedPath); got != tc.want {
			t.Errorf("quoteURI(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

// The "%" case above is why decodeURI exists and why it must run first. java.net.URI's
// accessors hand joinURI the DECODED path, so decode-then-quote is IDEMPOTENT on any
// well-formed escape: "%20" is a space by the time quoting happens and comes back "%20", and
// "%25" is a single '%' that comes back "%25". Quoting the raw text without decoding is what
// doubles an escape into "%2520", and that was a real defect in this port - caught by golden
// xmlbase-escaped.c14n11.apex-m, which Santuario says is "http://x/a%20b/c/d/". This test
// checks the two halves compose the way that golden requires, so the defect cannot return
// via a caller that skips decodeURI.
func TestDecodeThenQuoteIsTheJavaRoundTrip(t *testing.T) {
	cases := []struct{ raw, want string }{
		{"a%20b", "a%20b"}, // space decodes then re-quotes to itself
		{"a%2Fb", "a/b"},   // an escaped slash decodes to a real separator
		{"a%25b", "a%25b"}, // a literal percent decodes to '%' and quotes back to "%25"
		{"plain/path", "plain/path"},
	}
	for _, tc := range cases {
		if got := quoteURI(decodeURI(tc.raw), uriAllowedPath); got != tc.want {
			t.Errorf("quote(decode(%q)) = %q, want %q", tc.raw, got, tc.want)
		}
	}
}

// removeDotSegments is handed an empty path only by a hand-built DOM; through the parser the
// xmlbase-query KAT reaches it instead. Either way it must report the unjoinable error rather
// than panic the way Java's charAt(0) does.
func TestRemoveDotSegmentsEmptyPathIsUnjoinable(t *testing.T) {
	if _, err := removeDotSegments(""); !errors.Is(err, ErrXMLBaseUnjoinable) {
		t.Errorf("removeDotSegments(\"\") = %v, want ErrXMLBaseUnjoinable", err)
	}
	if _, err := joinURI("urn:opaque:x", true, "b/"); !errors.Is(err, ErrXMLBaseUnjoinable) {
		t.Errorf("joinURI with an opaque base = %v, want ErrXMLBaseUnjoinable", err)
	}
	if _, err := joinURI("http://x/a/", true, "urn:opaque:y"); !errors.Is(err, ErrXMLBaseUnjoinable) {
		t.Errorf("joinURI with an opaque reference = %v, want ErrXMLBaseUnjoinable", err)
	}
}

// outputAttributesPhysical is a backstop: Canonicalize refuses a physical node set before the
// walk starts, so the dispatch never reaches it in practice. Both layers are checked here.
func TestPhysicalRefusesNodeSetAtBothLayers(t *testing.T) {
	doc, err := xmldom.Parse([]byte(`<r a="1"/>`), nil)
	if err != nil {
		t.Fatal(err)
	}
	subset := xmldom.NewNodeSet()
	subset.AddSubtree(doc)
	if _, err := CanonicalizeToBytes(C14NPhysical, Input{Node: doc, Subset: subset}); !errors.Is(err, ErrPhysicalNodeSet) {
		t.Errorf("Canonicalize = %v, want ErrPhysicalNodeSet", err)
	}
	e := &engine{physical: true}
	if err := e.outputAttributes(doc.DocumentElement(), newNSStack()); !errors.Is(err, ErrPhysicalNodeSet) {
		t.Errorf("outputAttributes = %v, want ErrPhysicalNodeSet", err)
	}
}

// A parsed document can never present an unjoinable xml:base without the KATs noticing, but
// the error must also survive the full Canonicalize call path rather than being swallowed
// into a silently wrong URI.
func TestUnjoinableXMLBasePropagatesOutOfCanonicalize(t *testing.T) {
	doc, err := xmldom.Parse([]byte(
		`<r xml:base="urn:example:a"><m xml:base="b/"><t Id="t"/></m></r>`), nil)
	if err != nil {
		t.Fatal(err)
	}
	var apex *xmldom.Node
	doc.Walk(func(n *xmldom.Node) bool {
		if n.Kind == xmldom.Element && n.AttrValue("", "Id") == "t" {
			apex = n
		}
		return true
	})
	if apex == nil {
		t.Fatal("apex not found")
	}
	if _, err := CanonicalizeNode(C14N11, apex); !errors.Is(err, ErrXMLBaseUnjoinable) {
		t.Errorf("C14N11 = %v, want ErrXMLBaseUnjoinable", err)
	}
	// The 1.0 branch does not join at all, so the same document canonicalizes cleanly and
	// keeps only the first xml:base it met.
	got, err := CanonicalizeNode(C14N10, apex)
	if err != nil {
		t.Fatalf("C14N10 = %v, want success", err)
	}
	if !strings.Contains(string(got), `xml:base="urn:example:a"`) {
		t.Errorf("C14N10 output %q lost the inherited xml:base", got)
	}
}
