package pdf

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"testing"
)

// TestPasswordBytes pins the charset step of
// StandardSecurityHandler.prepareForDecryption (passwordBytes): ISO-8859-1
// for /R 2-4 with '?' for anything Latin-1 cannot encode, UTF-8 for /R 5,
// SASLprep then UTF-8 for /R 6.
func TestPasswordBytes(t *testing.T) {
	cases := []struct {
		name string
		r    int
		in   string
		want []byte
	}{
		{"r2 ascii", 2, "secret", []byte("secret")},
		{"r3 latin-1", 3, "pässwort", []byte{0x70, 0xE4, 0x73, 0x73, 0x77, 0x6F, 0x72, 0x74}},
		{"r4 latin-1", 4, "café", []byte{0x63, 0x61, 0x66, 0xE9}},
		{"r4 above latin-1 becomes ?", 4, "caf€", []byte("caf?")},
		{"r4 supplementary is one ?", 4, "\U0001F600x", []byte("?x")},
		{"r4 malformed utf-8 is ?", 4, "caf\xE9", []byte("caf?")},
		{"r4 empty", 4, "", []byte{}},
		{"r5 utf-8 untouched", 5, "café", []byte("café")},
		{"r5 malformed utf-8 is U+FFFD", 5, "caf\xE9", []byte("caf\xEF\xBF\xBD")},
		{"r6 utf-8", 6, "café", []byte("café")},
		{"r6 saslprep maps", 6, "ﬁsh\u00ADca\u00A0fé", []byte("fishca fé")},
		{"r6 saslprep nfkc of fullwidth", 6, "ａｂ", []byte("ab")},
		{"r6 u+200b is a space, not nothing", 6, "a\u200Bb", []byte("a b")},
		{"r6 rtl only is fine", 6, "אב", []byte("אב")},
		// U+05FF is unassigned inside the Hebrew block: Java reports no
		// directionality for it, so it is neither RandALCat nor LCat and
		// "\u05FFa" is not mixed bidi text (pdfbox accepts it).
		{"r6 unassigned code point is neither R nor L", 6, "\u05FFa", []byte{0xD7, 0xBF, 0x61}},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got, err := passwordBytes([]byte(c.in), c.r)
			if err != nil {
				t.Fatalf("passwordBytes(%q, %d): %v", c.in, c.r, err)
			}
			if !bytes.Equal(got, c.want) {
				t.Errorf("passwordBytes(%q, %d) = % x, want % x", c.in, c.r, got, c.want)
			}
		})
	}

	prohibited := []struct {
		name string
		in   string
	}{
		{"ascii control", "a\x01b"},
		{"c1 control", "a\u0085b"},
		{"private use", "a\uE000b"},
		{"non-character", "a\uFDD0b"},
		{"replacement character", "a\uFFFDb"},
		{"tagging", "a\U000E0041b"},
		{"change display properties", "a\u200Eb"},
		{"rtl and ltr mixed", "אa"},
		{"rtl first, neutral last", "א1"},
		{"rtl first, unassigned last", "א\u05FF"},
		{"pdfbox (char) truncation: u+100a0 reads as u+00a0", "a\U000100A0b"},
	}
	for _, c := range prohibited {
		t.Run("prohibited "+c.name, func(t *testing.T) {
			_, err := passwordBytes([]byte(c.in), 6)
			if !errors.Is(err, ErrProhibitedPassword) {
				t.Errorf("passwordBytes(%q, 6): err = %v, want ErrProhibitedPassword", c.in, err)
			}
			// Below /R 6 no SASLprep runs, so the same text is accepted.
			if _, err := passwordBytes([]byte(c.in), 4); err != nil {
				t.Errorf("passwordBytes(%q, 4): %v, want no error (no SASLprep below R6)", c.in, err)
			}
		})
	}
}

// TestPasswordCharsetFixtures is the known-answer test for the same step
// against documents pdfbox 3.0.6 itself protected (testdata/password,
// generated by PasswordFixtures.java there): every one opens with the text
// pdfbox protected it with, the owner password yields owner access, and the
// byte forms pdfbox would NOT have hashed are refused with
// ErrInvalidPassword - which pins the "Options.Password is UTF-8 text"
// contract from both sides.
func TestPasswordCharsetFixtures(t *testing.T) {
	cases := []struct {
		file     string
		password string
		owner    bool
		wantErr  error
	}{
		// /V 2 /R 3, RC4: user "café", owner "ownér".
		{"rc4_r3_latin1.pdf", "café", false, nil},
		{"rc4_r3_latin1.pdf", "ownér", true, nil},
		{"rc4_r3_latin1.pdf", "caf\xE9", false, ErrInvalidPassword}, // raw Latin-1 bytes are not the text
		{"rc4_r3_latin1.pdf", "cafe", false, ErrInvalidPassword},
		// /V 4 /R 4, AES-128: same passwords.
		{"aes128_r4_latin1.pdf", "café", false, nil},
		{"aes128_r4_latin1.pdf", "ownér", true, nil},
		{"aes128_r4_latin1.pdf", "caf\xE9", false, ErrInvalidPassword},
		{"aes128_r4_latin1.pdf", "", false, ErrInvalidPassword},
		// /V 4 /R 4 protected with "caf€": ISO-8859-1 made that "caf?", so
		// both texts open it and only the '?' form is what is hashed.
		{"aes128_r4_unmappable.pdf", "caf€", false, nil},
		{"aes128_r4_unmappable.pdf", "caf?", false, nil},
		{"aes128_r4_unmappable.pdf", "caf\xE2\x82", false, ErrInvalidPassword}, // truncated UTF-8: two '?'
		{"aes128_r4_unmappable.pdf", "owner", true, nil},
		// /V 5 /R 6, AES-256: UTF-8, no transcoding.
		{"aes256_r6_utf8.pdf", "café", false, nil},
		{"aes256_r6_utf8.pdf", "ownér", true, nil},
		{"aes256_r6_utf8.pdf", "caf?", false, ErrInvalidPassword},
		// Malformed UTF-8 is U+FFFD as text, which SASLprep prohibits: a Java
		// String can never carry it, so pdfbox has no answer for this input
		// and refusing it outright is the coherent one.
		{"aes256_r6_utf8.pdf", "caf\xE9", false, ErrProhibitedPassword},
		// /V 5 /R 6 protected with "ﬁsh<soft hyphen>ca<no-break space>fé",
		// which SASLprep turns into "fishca fé" on both sides.
		{"aes256_r6_saslprep.pdf", "ﬁsh\u00ADca\u00A0fé", false, nil},
		{"aes256_r6_saslprep.pdf", "fishca fé", false, nil},
		{"aes256_r6_saslprep.pdf", "fishcafé", false, ErrInvalidPassword},
		{"aes256_r6_saslprep.pdf", "owner", true, nil},
		{"aes256_r6_saslprep.pdf", "own\x01er", false, ErrProhibitedPassword},
	}
	for _, c := range cases {
		t.Run(c.file+"/"+c.password, func(t *testing.T) {
			data, err := os.ReadFile(filepath.Join("testdata", "password", c.file))
			if err != nil {
				t.Fatal(err)
			}
			doc, err := OpenBytes(data, &Options{Password: []byte(c.password)})
			if c.wantErr != nil {
				if !errors.Is(err, c.wantErr) {
					t.Fatalf("OpenBytes: err = %v, want %v", err, c.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("OpenBytes: %v", err)
			}
			if !doc.IsEncrypted() {
				t.Fatal("document reports itself as not encrypted")
			}
			if got := doc.Permissions().OwnerAccess; got != c.owner {
				t.Errorf("OwnerAccess = %v, want %v", got, c.owner)
			}
		})
	}
}
