package xades

import (
	"testing"

	"github.com/ryftcore/dss-go/dss/enumerations"
	"github.com/ryftcore/dss-go/dss/model"
	"github.com/ryftcore/dss-go/dss/utils"
)

// The KAT for the counter-signature flow, compared against upstream DSS 6.5.RC1's own output
// (testdata/sign-a-builder.txt, case "counter-signature", generated by gen/SignABuilderOracle.java
// with the same fixed inputs as the signature-builder KAT).
//
// The oracle records, in the order XAdESService#counterSignSignature drives them:
//
//	master-document              the enveloping signature that gets counter-signed
//	deterministic-id             XAdESCounterSignatureParameters#getDeterministicId
//	canonicalized-signature-value  GetCanonicalizedSignatureValue
//	reference-*                  every field BuildCounterSignatureDSSReference sets
//	counter-signature-document   the enveloping signature over that canonicalized SignatureValue
//	embedded-document            BuildEmbeddedCounterSignature's result
//
// Upstream reuses one CounterSignatureBuilder instance across the three calls, because only
// GetCanonicalizedSignatureValue assigns params; this test does the same.

// xadesCounterSignatureMasterDocument rebuilds the signature to be counter-signed, and checks it
// is byte-identical to the one the oracle counter-signed.
func xadesCounterSignatureMasterDocument(t *testing.T,
	oracle xadesSignABuilderOracle) (model.DSSDocument, *SignatureParameters) {
	t.Helper()
	masterParams := xadesSignABuilderEnvelopingParams(t)
	builderRef, err := SignatureBuilderGetSignatureBuilder(masterParams,
		xadesSignABuilderTextDocument(), xadesSignABuilderVerifier())
	if err != nil {
		t.Fatalf("building the master signature builder: %v", err)
	}
	if _, err := builderRef.Build(); err != nil {
		t.Fatalf("building the master signature: %v", err)
	}
	master, err := builderRef.SignDocument(xadesSignABuilderSignatureValue())
	if err != nil {
		t.Fatalf("signing the master signature: %v", err)
	}
	xadesSignABuilderAssertBytes(t, "counter-signature", "master-document",
		oracle.expect(t, "counter-signature", "master-document"),
		xadesSignABuilderReadAll(t, master))
	return master, masterParams
}

// xadesCounterSignatureParams mirrors SignABuilderOracle's counter-signature parameters.
func xadesCounterSignatureParams(t *testing.T,
	signatureIdToCounterSign string) *CounterSignatureParameters {
	t.Helper()
	params := NewXAdESCounterSignatureParameters()
	signer := xadesSignABuilderSigner(t)
	params.SetSigningCertificate(signer)
	params.SetCertificateChain([]*model.CertificateToken{signer})
	signingDate := xadesSignABuilderSigningDate
	params.BLevel().SetSigningDate(&signingDate)
	params.SetSignatureLevel(enumerations.SignatureLevelXAdESBaselineB)
	params.SetSignaturePackaging(enumerations.SignaturePackagingEnveloped)
	params.SetDigestAlgorithm(enumerations.DigestAlgorithmSHA256)
	params.SetSignatureIdToCounterSign(signatureIdToCounterSign)
	return params
}

func TestCounterSignatureBuilderAgainstJavaOracle(t *testing.T) {
	oracle := loadXAdESSignABuilderOracle(t)

	master, masterParams := xadesCounterSignatureMasterDocument(t, oracle)
	counterParams := xadesCounterSignatureParams(t, masterParams.GetDeterministicId())

	// The overridden deterministic Id: built from the signing date, the signing certificate and
	// the Id of the signature being counter-signed.
	if got := counterParams.GetDeterministicId(); got !=
		string(oracle.expect(t, "counter-signature", "deterministic-id")) {
		t.Errorf("GetDeterministicId() = %q, want %q", got,
			oracle.expect(t, "counter-signature", "deterministic-id"))
	}

	builder := NewCounterSignatureBuilder(xadesSignABuilderVerifier())

	canonicalizedSignatureValue, err := builder.GetCanonicalizedSignatureValue(master, counterParams)
	if err != nil {
		t.Fatalf("GetCanonicalizedSignatureValue: %v", err)
	}
	xadesSignABuilderAssertBytes(t, "counter-signature", "canonicalized-signature-value",
		oracle.expect(t, "counter-signature", "canonicalized-signature-value"),
		xadesSignABuilderReadAll(t, canonicalizedSignatureValue))

	// Same builder instance, as XAdESService#counterSignSignature does.
	reference, err := builder.BuildCounterSignatureDSSReference(master, counterParams)
	if err != nil {
		t.Fatalf("BuildCounterSignatureDSSReference: %v", err)
	}
	if got, want := reference.Id(), string(oracle.expect(t, "counter-signature", "reference-id")); got != want {
		t.Errorf("reference Id = %q, want %q", got, want)
	}
	if got, want := reference.Uri(), string(oracle.expect(t, "counter-signature", "reference-uri")); got != want {
		t.Errorf("reference URI = %q, want %q", got, want)
	}
	if got, want := reference.Type(), string(oracle.expect(t, "counter-signature", "reference-type")); got != want {
		t.Errorf("reference Type = %q, want %q", got, want)
	}
	if got, want := string(reference.DigestMethodAlgorithm()),
		string(oracle.expect(t, "counter-signature", "reference-digest-method")); got != want {
		t.Errorf("reference DigestMethodAlgorithm = %q, want %q", got, want)
	}
	xadesSignABuilderAssertBytes(t, "counter-signature", "reference-contents",
		oracle.expect(t, "counter-signature", "reference-contents"),
		xadesSignABuilderReadAll(t, reference.Contents()))
	transforms := reference.Transforms()
	if len(transforms) != 1 {
		t.Fatalf("reference carries %d transforms, want 1", len(transforms))
	}
	if got, want := transforms[0].Algorithm(),
		string(oracle.expect(t, "counter-signature", "reference-transform")); got != want {
		t.Errorf("reference transform = %q, want %q", got, want)
	}

	// The counter signature itself: an enveloping signature over the canonicalized SignatureValue.
	embeddedParams := xadesSignABuilderEnvelopingParams(t)
	counterBuilderRef, err := SignatureBuilderGetSignatureBuilder(embeddedParams,
		canonicalizedSignatureValue, xadesSignABuilderVerifier())
	if err != nil {
		t.Fatalf("building the counter-signature builder: %v", err)
	}
	if _, err := counterBuilderRef.Build(); err != nil {
		t.Fatalf("building the counter signature: %v", err)
	}
	counterSignature, err := counterBuilderRef.SignDocument(xadesSignABuilderSignatureValue())
	if err != nil {
		t.Fatalf("signing the counter signature: %v", err)
	}
	xadesSignABuilderAssertBytes(t, "counter-signature", "counter-signature-document",
		oracle.expect(t, "counter-signature", "counter-signature-document"),
		xadesSignABuilderReadAll(t, counterSignature))

	counterParams.SetReferences([]*DSSReference{reference})

	embedBuilder := NewCounterSignatureBuilder(xadesSignABuilderVerifier())
	embedded, err := embedBuilder.BuildEmbeddedCounterSignature(master, counterSignature, counterParams)
	if err != nil {
		t.Fatalf("BuildEmbeddedCounterSignature: %v", err)
	}
	xadesSignABuilderAssertBytes(t, "counter-signature", "embedded-document",
		oracle.expect(t, "counter-signature", "embedded-document"),
		xadesSignABuilderReadAll(t, embedded))
}

// TestCounterSignatureBuilderUnknownSignatureId covers the "signature not found" branch of
// extractSignatureById, which Java raises as an IllegalArgumentException.
func TestCounterSignatureBuilderUnknownSignatureId(t *testing.T) {
	oracle := loadXAdESSignABuilderOracle(t)
	master, _ := xadesCounterSignatureMasterDocument(t, oracle)

	counterParams := xadesCounterSignatureParams(t, "id-does-not-exist")
	builder := NewCounterSignatureBuilder(xadesSignABuilderVerifier())

	_, err := builder.GetCanonicalizedSignatureValue(master, counterParams)
	if err == nil {
		t.Fatal("counter-signing an unknown signature Id must fail")
	}
	want := "A signature with Id 'id-does-not-exist' has not been found in the file! Unable to counter sign."
	if err.Error() != want {
		t.Errorf("error = %q, want %q", err.Error(), want)
	}
}

// TestCounterSignatureBuilderRequiresSignatureId covers the Objects.requireNonNull guard, which
// the port keeps as a panic carrying the Java message.
func TestCounterSignatureBuilderRequiresSignatureId(t *testing.T) {
	oracle := loadXAdESSignABuilderOracle(t)
	master, _ := xadesCounterSignatureMasterDocument(t, oracle)

	counterParams := xadesCounterSignatureParams(t, "")
	builder := NewCounterSignatureBuilder(xadesSignABuilderVerifier())

	defer func() {
		recovered := recover()
		if recovered == nil {
			t.Fatal("a missing signatureIdToCounterSign must panic")
		}
		message, ok := recovered.(string)
		if !ok || !utils.IsStringNotEmpty(message) {
			t.Fatalf("unexpected panic value %v", recovered)
		}
		want := "The Id of a signature to be counter signed shall be defined! " +
			"Please use SerializableCounterSignatureParameters.setSignatureIdToCounterSign(signatureId) method."
		if message != want {
			t.Errorf("panic message = %q, want %q", message, want)
		}
	}()

	_, _ = builder.GetCanonicalizedSignatureValue(master, counterParams)
}

// TestXAdESCounterSignatureParametersDefaults pins the default canonicalization method and the
// accessors the SerializableCounterSignatureParameters interface requires.
func TestXAdESCounterSignatureParametersDefaults(t *testing.T) {
	params := NewXAdESCounterSignatureParameters()
	if got := params.CounterSignatureCanonicalizationMethod(); got !=
		"http://www.w3.org/2001/10/xml-exc-c14n#" {
		t.Errorf("default counter-signature canonicalization method = %q", got)
	}
	params.SetCounterSignatureCanonicalizationMethod("http://www.w3.org/TR/2001/REC-xml-c14n-20010315")
	if got := params.CounterSignatureCanonicalizationMethod(); got !=
		"http://www.w3.org/TR/2001/REC-xml-c14n-20010315" {
		t.Errorf("SetCounterSignatureCanonicalizationMethod did not take: %q", got)
	}
	params.SetSignatureIdToCounterSign("id-1")
	if got := params.SignatureIdToCounterSign(); got != "id-1" {
		t.Errorf("SignatureIdToCounterSign = %q, want %q", got, "id-1")
	}
}
