package xades

import (
	"testing"

	"github.com/utain/esig/dss/enumerations"
	"github.com/utain/esig/dss/model"
	"github.com/utain/esig/dss/xml/common"
)

// TestManifestBuilderAgainstJavaOracle compares the ds:Manifest documents against upstream DSS
// 6.5.RC1's own output (testdata/sign-a-builder.txt, generated by gen/SignABuilderOracle.java).
// The three cases exercise the default id and namespace, a custom id with SHA-512 references, and
// a custom xmldsig prefix.
func TestManifestBuilderAgainstJavaOracle(t *testing.T) {
	oracle := loadXAdESSignABuilderOracle(t)

	t.Run("manifest-default", func(t *testing.T) {
		builder, err := NewManifestBuilder(enumerations.DigestAlgorithm_SHA256,
			[]model.DSSDocument{xadesSignABuilderTextDocument(), xadesSignABuilderXMLDocument()})
		if err != nil {
			t.Fatalf("NewManifestBuilder: %v", err)
		}
		manifest, err := builder.Build()
		if err != nil {
			t.Fatalf("Build: %v", err)
		}
		xadesSignABuilderAssertBytes(t, "manifest-default", "document",
			oracle.expect(t, "manifest-default", "document"),
			xadesSignABuilderReadAll(t, manifest))
	})

	t.Run("manifest-named-sha512", func(t *testing.T) {
		builder, err := NewManifestBuilderWithId("my-manifest", enumerations.DigestAlgorithm_SHA512,
			[]model.DSSDocument{xadesSignABuilderTextDocument()})
		if err != nil {
			t.Fatalf("NewManifestBuilderWithId: %v", err)
		}
		manifest, err := builder.Build()
		if err != nil {
			t.Fatalf("Build: %v", err)
		}
		xadesSignABuilderAssertBytes(t, "manifest-named-sha512", "document",
			oracle.expect(t, "manifest-named-sha512", "document"),
			xadesSignABuilderReadAll(t, manifest))
	})

	t.Run("manifest-custom-namespace", func(t *testing.T) {
		builder, err := NewManifestBuilderWithNamespace("prefixed", enumerations.DigestAlgorithm_SHA256,
			[]model.DSSDocument{xadesSignABuilderTextDocument()},
			common.NewDSSNamespace(common.XMLDSigNS.Uri(), "dsig"))
		if err != nil {
			t.Fatalf("NewManifestBuilderWithNamespace: %v", err)
		}
		manifest, err := builder.Build()
		if err != nil {
			t.Fatalf("Build: %v", err)
		}
		xadesSignABuilderAssertBytes(t, "manifest-custom-namespace", "document",
			oracle.expect(t, "manifest-custom-namespace", "document"),
			xadesSignABuilderReadAll(t, manifest))
	})
}

// TestManifestBuilderRejectsEmptyInput covers the two IllegalArgumentException guards, which the
// port turns into constructor errors.
func TestManifestBuilderRejectsEmptyInput(t *testing.T) {
	if _, err := NewManifestBuilder(enumerations.DigestAlgorithm_SHA256, nil); err == nil {
		t.Error("an empty document list must be rejected")
	} else if err.Error() != "List of documents cannot be empty!" {
		t.Errorf("unexpected message: %q", err.Error())
	}

	if _, err := NewManifestBuilderWithReferences(nil); err == nil {
		t.Error("an empty reference list must be rejected")
	} else if err.Error() != "List of references cannot be empty!" {
		t.Errorf("unexpected message: %q", err.Error())
	}
}

// TestManifestBuilderManifestReferences checks that the references the builder derived from the
// documents are the ones it exposes, in order - the accessor ASiC relies on.
func TestManifestBuilderManifestReferences(t *testing.T) {
	builder, err := NewManifestBuilder(enumerations.DigestAlgorithm_SHA256,
		[]model.DSSDocument{xadesSignABuilderTextDocument(), xadesSignABuilderXMLDocument()})
	if err != nil {
		t.Fatalf("NewManifestBuilder: %v", err)
	}
	references := builder.ManifestReferences()
	if len(references) != 2 {
		t.Fatalf("ManifestReferences() returned %d references, want 2", len(references))
	}
	if references[0].Uri() != "hello.txt" || references[1].Uri() != "sample.xml" {
		t.Errorf("unexpected reference URIs: %q, %q", references[0].Uri(), references[1].Uri())
	}
	if references[0].Id() != "r-manifest-1" || references[1].Id() != "r-manifest-2" {
		t.Errorf("unexpected reference Ids: %q, %q", references[0].Id(), references[1].Id())
	}
}
