package xades

import (
	"testing"

	xmlutils "github.com/utain/esig/dss/xml/utils"
)

// TestPrettyPrintTransformerAgainstJavaOracle compares the indented DOM against upstream DSS
// 6.5.RC1's own output (testdata/sign-a-builder.txt, generated by gen/SignABuilderOracle.java).
//
// The pretty-drop-indents-preindented case is the interesting one: upstream discards the value
// removeSiblingIndents returns, so the walk stops at the first stripped text run and leaves the
// rest of the child list untouched. That behaviour is what these bytes pin.
func TestPrettyPrintTransformerAgainstJavaOracle(t *testing.T) {
	oracle := loadXAdESSignABuilderOracle(t)

	cases := []struct {
		name                string
		keepOriginalIndents bool
		indentAmount        int
		xml                 string
	}{
		{"pretty-keep-indents", true, 4, "<a><b>text</b><c/></a>"},
		{"pretty-keep-indents-preindented", true, 4, "<a>\n  <b>text</b>\n  <c/>\n</a>"},
		{"pretty-drop-indents-preindented", false, 4, "<a>\n  <b>text</b>\n  <c/>\n</a>"},
		{"pretty-indent-2", true, 2, "<a><b><c>deep</c></b></a>"},
		{"pretty-mixed-content", true, 4, "<a>lead<b>text</b>tail</a>"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			document, err := xmlutils.DomUtilsBuildDOMFromString(tc.xml)
			if err != nil {
				t.Fatalf("parsing the input: %v", err)
			}
			result := NewPrettyPrintTransformer().
				SetKeepOriginalIndents(tc.keepOriginalIndents).
				SetIndentAmount(tc.indentAmount).
				Transform(document.DocumentElement())
			serialized, err := xmlutils.DomUtilsSerializeNode(result)
			if err != nil {
				t.Fatalf("serializing the result: %v", err)
			}
			xadesSignABuilderAssertBytes(t, tc.name, "node", oracle.expect(t, tc.name, "node"), serialized)
		})
	}
}

// TestPrettyPrintTransformerDoesNotModifyInput checks the clone-first contract of #transform: the
// node handed in is left exactly as it was.
func TestPrettyPrintTransformerDoesNotModifyInput(t *testing.T) {
	document, err := xmlutils.DomUtilsBuildDOMFromString("<a><b>text</b></a>")
	if err != nil {
		t.Fatalf("parsing the input: %v", err)
	}
	before, err := xmlutils.DomUtilsSerializeNode(document.DocumentElement())
	if err != nil {
		t.Fatalf("serializing the input: %v", err)
	}

	NewPrettyPrintTransformer().Transform(document.DocumentElement())

	after, err := xmlutils.DomUtilsSerializeNode(document.DocumentElement())
	if err != nil {
		t.Fatalf("serializing the input again: %v", err)
	}
	if string(before) != string(after) {
		t.Errorf("Transform modified its input\nbefore: %s\nafter:  %s", before, after)
	}
}

// TestPrettyPrintTransformerDefaults pins the two constructor defaults - four spaces of indent and
// keepOriginalIndents - through observable behaviour rather than by reading the fields.
func TestPrettyPrintTransformerDefaults(t *testing.T) {
	if DSSXMLUtilsTransformerIndentNumber != 4 {
		t.Fatalf("DSSXMLUtilsTransformerIndentNumber = %d, want 4",
			DSSXMLUtilsTransformerIndentNumber)
	}

	document, err := xmlutils.DomUtilsBuildDOMFromString("<a><b/></a>")
	if err != nil {
		t.Fatalf("parsing the input: %v", err)
	}
	result := NewPrettyPrintTransformer().Transform(document.DocumentElement())
	serialized, err := xmlutils.DomUtilsSerializeNode(result)
	if err != nil {
		t.Fatalf("serializing the result: %v", err)
	}
	want := `<?xml version="1.0" encoding="UTF-8"?><a>` + "\n    <b/>\n" + `</a>`
	if string(serialized) != want {
		t.Errorf("default indentation\nwant: %q\ngot:  %q", want, string(serialized))
	}
}
